const ANDESUR_DEFAULT_DATA = {
  "products": [
    {
      "id": 1,
      "name": "DVR 8CH 1080P ACUSENSE 1HDD CON ANALITICA (2)",
      "category": "CAMARAS ANALOGICAS",
      "model": "HK-DS7208HQHI-M1/XT",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 2,
      "name": "DISCO DURO PURPLE WD 1 TERA SATA",
      "category": "CAMARAS ANALOGICAS",
      "model": "SE-HDD1TB",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": ""
    },
    {
      "id": 3,
      "name": "DISCO DURO PURPLE WD 2 TERAS SATA",
      "category": "CAMARAS ANALOGICAS",
      "model": "SE-HDD2TB",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": ""
    },
    {
      "id": 4,
      "name": "FUENTE HIK VISION  1A- 12VDC",
      "category": "CAMARAS ANALOGICAS",
      "model": "HK-DS-2FA1201-DL",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 4
    },
    {
      "id": 5,
      "name": "VIDEO BALUN 4K (PAR) HIK VISION",
      "category": "CAMARAS ANALOGICAS",
      "model": "HIK VISION",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": ""
    },
    {
      "id": 6,
      "name": "FUENTE D@HUA 12V 2A",
      "category": "CAMARAS ANALOGICAS",
      "model": "HK-DS-1H18S/E",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 5
    },
    {
      "id": 7,
      "name": "REGLETA NEGRA 6 TOMAS CABLE 90 CM",
      "category": "CAMARAS ANALOGICAS",
      "model": "F2-FPS-001B",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": ""
    },
    {
      "id": 8,
      "name": "TURRET 2MP COLORVU SMART HYBRID LIGHT IR 20M 2.8MM C/AUDIO",
      "category": "CAMARAS ANALOGICAS",
      "model": "HK-DS2CE0DF0T-LPFS",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": ""
    },
    {
      "id": 9,
      "name": "BULLET 2MP COLORVU SMART HYBRID LIGHT IR 20M 2.8MM C/AUDIO",
      "category": "CAMARAS ANALOGICAS",
      "model": "HK-DS2CE1DF0T-LPFS",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": ""
    },
    {
      "id": 10,
      "name": "TURRET 5MP COLORVU SMART HYBRID LIGHT IR 20M 2.8MM C/AUDIO",
      "category": "CAMARAS ANALOGICAS",
      "model": "HK-DS2CE70KF0T-LPFS",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 11,
      "name": "BULLET 5MP COLORVU SMART HYBRID LIGHT IR20M 2.8MM C/AUDIO",
      "category": "CAMARAS ANALOGICAS",
      "model": "HK-DS2CE10KF0T-LFS",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 12,
      "name": "TURRET 5MP 3K SMART HYBRID LIGHT IR 20M 2.8MM C/AUDIO",
      "category": "CAMARAS ANALOGICAS",
      "model": "HK-DS2CE76K0T-LPFS",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": ""
    },
    {
      "id": 13,
      "name": "TUBO 2MP 1080P EXT CON IR 80M L3.6MM - 12VDC",
      "category": "CAMARAS ANALOGICAS",
      "model": "HK-DS2CE17D0T-IT5F",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": ""
    },
    {
      "id": 14,
      "name": "TUBO 5MP EXT CON IR 80M L3.6MM - 12VDC",
      "category": "CAMARAS ANALOGICAS",
      "model": "HK-DS2CE17H0T-IT5F",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": ""
    },
    {
      "id": 15,
      "name": "BULLET 1080P CON IR 20M L2.8MM",
      "category": "CAMARAS ANALOGICAS",
      "model": "HK-DS2CE16D0T-IRPF",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": ""
    },
    {
      "id": 16,
      "name": "TURRET 1080P IR 20M 2.8MM",
      "category": "CAMARAS ANALOGICAS",
      "model": "HK-DS2CE56D0T-IRPF",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 5
    },
    {
      "id": 17,
      "name": "PT 2MP SMART HYBRID LIGHT IR 25M 2.8MM AUDIO 2 VIAS",
      "category": "CAMARAS ANALOGICAS",
      "model": "HK-DS2CE70D0T-PTLTS",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": ""
    },
    {
      "id": 18,
      "name": "UPS 4 TOMAS  600VA",
      "category": "CAMARAS ANALOGICAS",
      "model": "UPS 4 TOMAS  600VA",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": ""
    },
    {
      "id": 19,
      "name": "Detector PIR",
      "category": "CAMARAS ANALOGICAS",
      "model": "DS-PDP15P-EG2-WB",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 20,
      "name": "Wireless Magnetic Contact",
      "category": "CAMARAS ANALOGICAS",
      "model": "DS-PD201MC-WB",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 21,
      "name": "CCTV POWER SUPPLY Multi-channel SMPS",
      "category": "CAMARAS ANALOGICAS",
      "model": "DS-2FA1225-C4",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 22,
      "name": "CCTV POWER SUPPLY Multi-channel SMPS",
      "category": "CAMARAS ANALOGICAS",
      "model": "DS-2FA1205-C8",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 23,
      "name": "Balun",
      "category": "CAMARAS ANALOGICAS",
      "model": "DS-1H18A",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 9
    },
    {
      "id": 24,
      "name": "CAM IP FT LENTE DUAL EXTERIOR 6MP WIFI LENTE 2.8+6MM",
      "category": "CAMARAS EZVIZ INALAMBRICAS",
      "model": "CS-H9C-R100-8H33WKFL",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 25,
      "name": "CAM IP 3MP INT C/BATERIA 4G 2000mAh",
      "category": "CAMARAS EZVIZ INALAMBRICAS",
      "model": "CS-CB2-R105-1K3F4GA-BK",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 26,
      "name": "CAM IP EXT 5MP WIFI LENTE 2.8MM",
      "category": "CAMARAS EZVIZ INALAMBRICAS",
      "model": "CS-H3C-R100-1J5WKFL",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 27,
      "name": "CAM IP EXT 3MP WIFI 2.4GHZ LENTE 2.8MM",
      "category": "CAMARAS EZVIZ INALAMBRICAS",
      "model": "CS-H3C-R100-1K3WKFL",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 28,
      "name": "CAM IP EXT 2MP WIFI 2.4GHZ LENTE 2.8MM",
      "category": "CAMARAS EZVIZ INALAMBRICAS",
      "model": ":CS-H3C-R100-1K2WFL",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 4
    },
    {
      "id": 29,
      "name": "CAM IP PT EXT 2MP WIFI 2.4GHZ LENTE 4MM",
      "category": "CAMARAS EZVIZ INALAMBRICAS",
      "model": "CS-H8C-R100-1K2WKFL",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 30,
      "name": "CAM IP PT INTER 2MP 1080P WIFI LENTE 4MM",
      "category": "CAMARAS EZVIZ INALAMBRICAS",
      "model": "CS-H6C-R105-1L2WF",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 31,
      "name": "CAM IP PT EXT 4MP WIFI 2.4GHZ LENTE 4MM",
      "category": "CAMARAS EZVIZ INALAMBRICAS",
      "model": "CS-H8C-R100-1J4WKFL",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 32,
      "name": "CAMARA IP PTZ 4MP LENTE 4MM (2)",
      "category": "CAMARAS EZVIZ INALAMBRICAS",
      "model": "CS-H6C-R105-1J4WF",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 33,
      "name": "CAM IP 2MP INTERIOR C/BATERIA 1600MAH WIFI LENTE 2.8MM",
      "category": "CAMARAS EZVIZ INALAMBRICAS",
      "model": "CS-CB1",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 34,
      "name": "CAM IP INT 1080P WIFI 2.4GHZ. LENTE FIJO 2.8MM",
      "category": "CAMARAS EZVIZ INALAMBRICAS",
      "model": "CS-H1C",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 35,
      "name": "CAM IP PT DUAL 4K + 2MP EXT LENTE 4MM",
      "category": "CAMARAS EZVIZ INALAMBRICAS",
      "model": "CS-H80X-R100-8G82WKFL",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 36,
      "name": "NVR 8CH SIN DISCO DURO WIFI",
      "category": "CAMARAS EZVIZ INALAMBRICAS",
      "model": "CS-X5S-8W",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 37,
      "name": "TOMACORRIENTE SMART",
      "category": "CAMARAS EZVIZ INALAMBRICAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 7
    },
    {
      "id": 38,
      "name": "MEMORIA MICRO SD 256GB NEO LUX",
      "category": "CAMARAS EZVIZ INALAMBRICAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 39,
      "name": "MEMORIA MICRO SD 128GB NEO LUX",
      "category": "CAMARAS EZVIZ INALAMBRICAS",
      "model": "HK-HS-TF-D3/128G",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": ""
    },
    {
      "id": 40,
      "name": "MICROSDXC MEMORY CARD 64 GB IMOU",
      "category": "CAMARAS EZVIZ INALAMBRICAS",
      "model": "MICROSDXC MEMORY CARD 64 GB IMOU",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": ""
    },
    {
      "id": 41,
      "name": "MICROSDXC MEMORY CARD 128GB SAN DISK",
      "category": "CAMARAS EZVIZ INALAMBRICAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 42,
      "name": "CMT-BRACKET-WALLMOUNT",
      "category": "CAMARAS EZVIZ INALAMBRICAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 43,
      "name": "SSD SATA 2.5 KINGSTON 960GB A400",
      "category": "DISCOS SOLIDOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 0
    },
    {
      "id": 44,
      "name": "SSD SATA 2.5 KINGSTON 480GB A400",
      "category": "DISCOS SOLIDOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 45,
      "name": "SSD SATA 2.5 KINGSTON 240GB A400",
      "category": "DISCOS SOLIDOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 0
    },
    {
      "id": 46,
      "name": "SSD M.2 KINGSTON 500GB NVME NV3, 2280",
      "category": "DISCOS SOLIDOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 47,
      "name": "SSD M.2 KINGSTON 1TB NVME NV3, 2280",
      "category": "DISCOS SOLIDOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 48,
      "name": "SSD  SATA  240 GB",
      "category": "DISCOS SOLIDOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 0
    },
    {
      "id": 49,
      "name": "WESTERN DIGITAL WD10PURZ 1TB",
      "category": "DISCOS SOLIDOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 0
    },
    {
      "id": 50,
      "name": "STAR SOLI SSD ST-400 120GB",
      "category": "DISCOS SOLIDOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 0
    },
    {
      "id": 51,
      "name": "WD GREEN SN350 250GB",
      "category": "DISCOS SOLIDOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 52,
      "name": "SSD Star, 120GB ST-400",
      "category": "DISCOS SOLIDOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 53,
      "name": "MEMORIA RAM FURY  DDR4 8GB",
      "category": "MEMORIAS RAM",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 54,
      "name": "MEMORIA RAM CORSAIR DDR4 16GB VENGEANCE LPX 3200 MHZ NEGRO",
      "category": "MEMORIAS RAM",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 55,
      "name": "MEMORIA PARA LAPTOP SODIMM KINGSTON DDR4 4GB 3200 MHZ",
      "category": "MEMORIAS RAM",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 56,
      "name": "MEMORIA PARA LAPTOP SODIMM KINGSTON DDR4 8GB 3200 MHZ",
      "category": "MEMORIAS RAM",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 57,
      "name": "TINTA 544  COMPATIBLE",
      "category": "TINTAS  PARA IMPRESORAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 58,
      "name": "TINTA 544  ORIGINAL",
      "category": "TINTAS  PARA IMPRESORAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 6
    },
    {
      "id": 59,
      "name": "TINTA 664  COMPATIBLE",
      "category": "TINTAS  PARA IMPRESORAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 6
    },
    {
      "id": 60,
      "name": "TINTA 664  ORIGINAL",
      "category": "TINTAS  PARA IMPRESORAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 4
    },
    {
      "id": 61,
      "name": "TINTA 504  COMPATIBLE",
      "category": "TINTAS  PARA IMPRESORAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 4
    },
    {
      "id": 62,
      "name": "TINTA 504  ORIGINAL",
      "category": "TINTAS  PARA IMPRESORAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 63,
      "name": "SMART-SERIE-500",
      "category": "TINTAS  PARA IMPRESORAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 5
    },
    {
      "id": 64,
      "name": "HIKVISION SMART MANAGED SWITCH 4 PORT",
      "category": "ACCESORIOS DE RED",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 65,
      "name": "ROUTER TPLINCK 300MPS",
      "category": "ACCESORIOS DE RED",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 66,
      "name": "SWITCH TP-LINCK  5 PUERTOS   10/100 MBPS",
      "category": "ACCESORIOS DE RED",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 67,
      "name": "SWITCH TP-LINCK  16 PUERTOS   10/100 MBPS",
      "category": "ACCESORIOS DE RED",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 68,
      "name": "HDTV SPLITTER 1X2",
      "category": "ACCESORIOS DE RED",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 69,
      "name": "HDTV SPLITTER 1X4",
      "category": "ACCESORIOS DE RED",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 70,
      "name": "TP-LINK DECO M4",
      "category": "ACCESORIOS DE RED",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 71,
      "name": "RJ45 AND RJ11 CABLE TESTER",
      "category": "ACCESORIOS DE RED",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 72,
      "name": "HIKVISION N360-WI-FI-ROUTER",
      "category": "ACCESORIOS DE RED",
      "model": "WR4G3N",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 73,
      "name": "KIT OFFICE WIRED- FUSSION ENT502",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "KIT OFFICE WIRED- FUSSION ENT502",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": ""
    },
    {
      "id": 74,
      "name": "COMBO ESCRITORIO: TECLADO/MOUSE",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "MOD HA-K429C",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 75,
      "name": "COMBO INALAMBRICO HALION",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "MOD HA-K204W",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": ""
    },
    {
      "id": 76,
      "name": "LOGITECH K120 CORDED",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 77,
      "name": "HEATSINK COMPOUNDS",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "HY510",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": ""
    },
    {
      "id": 78,
      "name": "CYBERTEL EBONY + CYB  K105+",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 79,
      "name": "LOGITECH M185",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 4
    },
    {
      "id": 80,
      "name": "LOGITECH M90",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 81,
      "name": "TEROS MOUSE OPTICO",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "TE-12265",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 4
    },
    {
      "id": 82,
      "name": "TEROS MOUSE INALAMBRICO",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "TE-12285",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 83,
      "name": "ENKORE URBAN",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "EKM-203W",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 84,
      "name": "ENKORE PIVOT",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "EKM-105W",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 85,
      "name": "HP MOUSE CABLEADO 100",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 86,
      "name": "ENKORE GEOX INGRAVIDE",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 87,
      "name": "MICRONICS KRIPTON 3MIC",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "GM801-3M",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 88,
      "name": "MICRONICS  DRAGON 3MIC",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "GM806-3M",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 89,
      "name": "MOUSE PAD CON DISEÑO",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 90,
      "name": "MOUSE PAD  NEGROS",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 91,
      "name": "EXTENDED MOUSE PAD",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 92,
      "name": "MOUSE PAD GAMER",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 93,
      "name": "ERGONOMIC MOUSE PAD",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 94,
      "name": "SCREEN PROTECTOR",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 6
    },
    {
      "id": 95,
      "name": "ESTUCHES PARA LAPTOP",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 9
    },
    {
      "id": 96,
      "name": "CARAGADOR DE LAPTOP",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 23
    },
    {
      "id": 97,
      "name": "PANTALLA ASUS",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 98,
      "name": "CYBERTEL XTREME TECLADO",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 99,
      "name": "TECLADO MICRONICS NEON",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 100,
      "name": "TECLADO MICRONICS AVANTY",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 101,
      "name": "TECLADO LOGITECH K120",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 102,
      "name": "TECLADO ENKORED FUSSION",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 103,
      "name": "TECLADO ENKORED BRAIN",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 104,
      "name": "TECLADO ENKORED BRAVID",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 105,
      "name": "CYBERTEL AESTETIC MOUSE",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 106,
      "name": "CYBERTELL GAMING KILLER",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 107,
      "name": "CYBERTELL GAMING HAMILTON",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 108,
      "name": "HP-160 GAMING MOUSE",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 109,
      "name": "AAIRBOOM AUREOLA",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 110,
      "name": "CASE PAR APC",
      "category": "ACCESORIOS DE PS/LAPTOP",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 111,
      "name": "HOCO EQ24",
      "category": "PARLANTES/AUDIFONOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 112,
      "name": "HOCO W40",
      "category": "PARLANTES/AUDIFONOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 113,
      "name": "HALION STEREO HEADPHONES T3",
      "category": "PARLANTES/AUDIFONOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 114,
      "name": "MICRONICS GAMER CORSAIR",
      "category": "PARLANTES/AUDIFONOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 115,
      "name": "MICRONICS GAMER IRON",
      "category": "PARLANTES/AUDIFONOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 116,
      "name": "HAVIT",
      "category": "PARLANTES/AUDIFONOS",
      "model": "HAVIT",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": ""
    },
    {
      "id": 117,
      "name": "JBL",
      "category": "PARLANTES/AUDIFONOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 118,
      "name": "E-1053",
      "category": "PARLANTES/AUDIFONOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 119,
      "name": "HA-STEREO-HEADPHONES",
      "category": "PARLANTES/AUDIFONOS",
      "model": "HA-H856",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 120,
      "name": "HA-STEREO-HEADPHONES-HA",
      "category": "PARLANTES/AUDIFONOS",
      "model": "S7R",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 121,
      "name": "ESTABILIZADOR FORZA 900VA 8 TOMAS, CAPACIDAD 900VA / 450W",
      "category": "FUENTES DE PODER/ESTABILISADOR",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 4
    },
    {
      "id": 122,
      "name": "ESTABILIZADOR FORZA 1200VA 8 TOMAS Y 2 PUERTOS USB, CAPACIDAD 1200VA / 600 W",
      "category": "FUENTES DE PODER/ESTABILISADOR",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 0
    },
    {
      "id": 123,
      "name": "POWER SUPPLY 80PLUS WHITE G650W",
      "category": "FUENTES DE PODER/ESTABILISADOR",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 124,
      "name": "POWER SUPPY PSA-F600W",
      "category": "FUENTES DE PODER/ESTABILISADOR",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 125,
      "name": "CYBERCOOL HA-69 NOTEBOOK STAND & COOLNG PAD",
      "category": "FUENTES DE PODER/ESTABILISADOR",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 126,
      "name": "AIRCOM BOREAL",
      "category": "FUENTES DE PODER/ESTABILISADOR",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 127,
      "name": "FORZA SUPRESOR DE PICOS",
      "category": "FUENTES DE PODER/ESTABILISADOR",
      "model": "PS-001B",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 6
    },
    {
      "id": 128,
      "name": "SMART CARD READER  PC/SC CCID ISO7816 USB",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 129,
      "name": "MODEM USB ZTE MF833U1",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 130,
      "name": "\"2.5\" HDD EXTERNAL CASE",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 131,
      "name": "FLEXIBLE KEYBOARD",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 132,
      "name": "NIVERSAL BIKE HLDER",
      "category": "ACCESORIOS",
      "model": "CH-01",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 133,
      "name": "TRIPODE MINI ROSA",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 134,
      "name": "HDTV 2.0, CABLE HDMI 4K",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 135,
      "name": "ALL IN ONE MEMORY CARD READER",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 136,
      "name": "WATERPROOF POUCH",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 137,
      "name": "ADAPTADOR DE AUDIO JACK 3.5MM",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 138,
      "name": "FUNDA DE AIRPODS",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 139,
      "name": "CABLE USB",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 140,
      "name": "USB 16GB PHILIPS",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 141,
      "name": "USB 16GB DAHUA",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 142,
      "name": "MU RATA CR2030",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 143,
      "name": "BLUETHOOT USD ADAPTER",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 144,
      "name": "HALION K19 TECLADO NUMERICO",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 145,
      "name": "CARD READER-480Mbps USB2.0",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 146,
      "name": "2 IN 1 CARD READER",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 147,
      "name": "USD 3.0 HUB 4 PORTS",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 148,
      "name": "OPALUX-ST-96",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 149,
      "name": "HDMI-EXTENDER BY CAT-6/6E CABLE",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 150,
      "name": "USBC TO HEADPHONE JACK ADAPTER",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 151,
      "name": "ACC-C2A USB-C TO USB-A ADAPTER",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 152,
      "name": "CAR-WIRELES",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 153,
      "name": "CARGADOR USB-C HOCO-C109",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 4
    },
    {
      "id": 154,
      "name": "STEREO BASS M97",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 5
    },
    {
      "id": 155,
      "name": "MOBILE PHONE OGT CONECT KIT-K07",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 156,
      "name": "HDMI TO VGA ADAPTER",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 157,
      "name": "POWER ADAPTER 12V/DC",
      "category": "ACCESORIOS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 8
    },
    {
      "id": 158,
      "name": "POWER ADAPTER",
      "category": "ACCESORIOS",
      "model": "DH-PFM320D-US",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 8
    },
    {
      "id": 159,
      "name": "VGA TO VGA CABLE",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 10
    },
    {
      "id": 160,
      "name": "CABLE DE PODER TIPO TREBOL",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 10
    },
    {
      "id": 161,
      "name": "CABLE DE PODER TIPO 8 PARA IMPRESORA",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 9
    },
    {
      "id": 162,
      "name": "CABLE DE PODER PARA PC",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 12
    },
    {
      "id": 163,
      "name": "100 UNIDADES CONECTORES DC HEMBRA",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 164,
      "name": "100 UNIDADES CONECTORES DC MACHO",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 165,
      "name": "ADAPTADOR ELECTRICO DE 2 PINES GLUX",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 10
    },
    {
      "id": 166,
      "name": "ADAPTADOR MULTIPLE DE 2 PINES",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 167,
      "name": "CAJA MODULAR 2X4",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 26
    },
    {
      "id": 168,
      "name": "CAJA DE PASO",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 169,
      "name": "FUENTE 1A",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 170,
      "name": "TOMA DE RED RJ45",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 10
    },
    {
      "id": 171,
      "name": "TOMACORRIENTE DOBLE UNIVERSAL",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 172,
      "name": "TOMACORRIENTE TRIPLE",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 12
    },
    {
      "id": 173,
      "name": "GRAPAS PARA CONCRETO 100UND",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 174,
      "name": "BRAZOS SOPORTES TIPO L PARA CÁMARAS CCTV",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 3
    },
    {
      "id": 175,
      "name": "FAJOS DE CANALETAS PVC PARA CABLEADO 20X12",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 4
    },
    {
      "id": 176,
      "name": "PARA RACK",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 177,
      "name": "ROLLO TUBO CORRUGADO",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 178,
      "name": "CABLE TW-80 CALIBRE 12AWG ROJO",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 179,
      "name": "CABLE TW-80 CALIBRE 12AWG BLANCO",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 180,
      "name": "CABLE TW-80 CALIBRE 14AWG AZUL",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 181,
      "name": "CABLE TW-80 CALIBRE 10AWG NEGRO",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 182,
      "name": "CABLE HDMI 15 METROS",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 4
    },
    {
      "id": 183,
      "name": "CABLE HDMI  10 METROS",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 184,
      "name": "PAQUETES DE CINTILLOS",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 8
    },
    {
      "id": 185,
      "name": "CABLE USB-A TO USB-B",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 186,
      "name": "GABINETE 4RU",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    },
    {
      "id": 187,
      "name": "GABINETE 9RU",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 188,
      "name": "JUEGO DE PUNTAS PHILLIPS PH2 PARA TALADRO/ATORNILLADOR",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "SIN CÓDIGO",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 189,
      "name": "ENGRAMPADORA MANUAL 3 EN 1 INGO",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "HSG1405",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 1
    },
    {
      "id": 190,
      "name": "JUEGO DE DESARMADORES DE PRECISIÓN PRETUL",
      "category": "ACCESORIOS DE INSTALACIÓN Y HERRAMIENTAS",
      "model": "J-DEJ-6",
      "price": "",
      "oldPrice": "",
      "offer": "",
      "featured": false,
      "active": true,
      "image": "",
      "stock": 2
    }
  ],
  "services": [
    {
      "id": 101,
      "name": "Instalación de equipos",
      "category": "Instalación y puesta en marcha",
      "description": "Instalación y puesta en funcionamiento de los equipos que lo requieren.",
      "icon": "⚙",
      "active": true
    },
    {
      "id": 102,
      "name": "Mantenimiento preventivo",
      "category": "Mantenimiento y reparación",
      "description": "Revisión preventiva para ayudar a conservar tus electrodomésticos en buenas condiciones.",
      "icon": "◷",
      "active": true
    },
    {
      "id": 103,
      "name": "Reparación y diagnóstico",
      "category": "Mantenimiento y reparación",
      "description": "Diagnóstico y atención técnica para equipos que presentan fallas.",
      "icon": "✓",
      "active": true
    },
    {
      "id": 104,
      "name": "Asesoría de productos",
      "category": "Asesoría y soporte",
      "description": "Orientación para elegir el equipo adecuado según tus necesidades y presupuesto.",
      "icon": "i",
      "active": true
    },
    {
      "id": 105,
      "name": "Soporte y uso",
      "category": "Asesoría y soporte",
      "description": "Acompañamiento para utilizar correctamente tus productos y resolver dudas.",
      "icon": "?",
      "active": true
    }
  ],
  "company": {
    "name": "Andesur",
    "email": "ventas@andesur.pe",
    "phone": "+51 963 925 684",
    "address": "Jr. Real 480, Huancayo, Junín — Perú",
    "description": "Electrodomésticos con garantía real y servicio técnico propio."
  }
};

function getSiteData(){
  try {
    const saved = localStorage.getItem('andesur_site_data');
    const version = localStorage.getItem('andesur_inventory_version');
    if(!saved || version !== 'inventario-2026-09-12'){
      const fresh = {
        products: JSON.parse(JSON.stringify(ANDESUR_DEFAULT_DATA.products)),
        services: JSON.parse(JSON.stringify(ANDESUR_DEFAULT_DATA.services)),
        company: JSON.parse(JSON.stringify(ANDESUR_DEFAULT_DATA.company))
      };
      localStorage.setItem('andesur_inventory_version','inventario-2026-09-12');
      return fresh;
    }
    const parsed = JSON.parse(saved);
    parsed.products = Array.isArray(parsed.products) ? parsed.products : JSON.parse(JSON.stringify(ANDESUR_DEFAULT_DATA.products));
    return {
      products: parsed.products,
      services: parsed.services || JSON.parse(JSON.stringify(ANDESUR_DEFAULT_DATA.services)),
      company: parsed.company || JSON.parse(JSON.stringify(ANDESUR_DEFAULT_DATA.company))
    };
  } catch(e) {
    return {
      products: JSON.parse(JSON.stringify(ANDESUR_DEFAULT_DATA.products)),
      services: JSON.parse(JSON.stringify(ANDESUR_DEFAULT_DATA.services)),
      company: JSON.parse(JSON.stringify(ANDESUR_DEFAULT_DATA.company))
    };
  }
}

function saveSiteData(data){
  localStorage.setItem('andesur_site_data', JSON.stringify(data));
  localStorage.setItem('andesur_inventory_version','inventario-2026-09-12');
}
